### ISSUE TITLE
[appserver-io/appserver] Pass environment variable to virtual-hosts.xml

### ISSUE THREAD

**Issue by DavidFeller** [appserver-io/appserver#1018]
We are running appserver.io inside of several identical docker containers to serve legacy applications like Magento. These containers are orchestrated by docker-compose. Currently we have to mount a host directory that contains a virtual-hosts.xml as a volume to /opt/appserver/etc/appserver/conf.d to be able to give each container an individual virtual host name. 

It would be great, if it was possible to just pass the virtual host name as an environment variable that can be defined in docker-compose.yml to the containers virtual-hosts.xml.

![appserver-vhost-config](https://cloud.githubusercontent.com/assets/2094727/15497667/093ef216-219c-11e6-9c3f-15a38d853ce2.png)

**Comment by wagnert** [comment]
Hi @DavidFeller,

i actually think about the best way of passing the Docker environment variables to the appserver.io configuration files. It would be possible to make all environment variables available in the appserver.io configuration files, as you can already use pre-defined variable names since version [1.1.1](http://appserver.io/get-started/documentation/1.1/configuration.html#configuration-variables).

Another, probably more pragmatic, solution would be a simple replacement using `sed` like 

```sh
RUN sed -i "s/VIRTUALHOST_NAME/appserver.local/g" etc/appserver/conf.d/virtual-hosts.xml
```

You can have a look at the appserver.io [Dockerfile](https://github.com/appserver-io/appserver/blob/master/Dockerfile) where we replaced the default values with Docker specific ones.

What do you think?
