### ISSUE TITLE
[appserver-io/appserver] DocumentRoot must be within webapps folder

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#750]
There have been several reports that configured document roots which are not located within the `webapps` directory result in unexpected behavior.
This seems to be related to servlets only so far.

Apps which are symlinked into the webapps directory e.g. with example -> /home/wick-ed/Workspace/example/src/ do produce a `404` if the `php-fpm` FasCGI backend tries to handle the issue.

**Comment by lekoala** [comment]
Hi there,

I've been trying to evaluate appserver to run apps, but I have precisely this issue, I don't see a good way to run apps that are outside the /webapps directory. Symbolic links do not seem to work properly (for plain files it's ok, but running php files fail).

I just get exception or file not found errors...

Would be really handy if there is a clear explanation on how to see a web root outside of appserver...

thanks,

**Comment by wick-ed** [comment]
Hi @lekoala ,

we know this is an issue we have to solve in future, but symlinking should work.
I for myself do only symlink apps into my `webapps` dir and did not face any issues so far.
Which OS are you on and which version of appserver.io do you evaluate?

I normally symlink the `src` directory of my app in e.g. `example -> /home/wick-ed/Workspace/example/src/`

**Comment by lekoala** [comment]
So maybe I'm doing something wrong, but here is what I do (testing on mac os 10.10, appserver 1.0.5):

- Copy example web app to another directory /Users/myuser/example
- Make a symlink ln -s /Users/myuser/example example2
- Make sure the owner and rights are the same for original and copied directory
- Change the virtual host to target example2 instead of example
- Restart appserver

Try to navigate to http://www.example.local:9080/phpinfo.php, I get a blank page with : "File not found.". Is there a way to "debug" how the request is resolved? (a bit like apache error.log?).

**Comment by wick-ed** [comment]
I can see where the issue is now.
In fact the `phpinfo.php` file does not work for me as well, but the example app does work in general.
Does it for you?
http://example.local:9080/index.do/messageQueue e.g. does work fine.
It seems that `php-fpm` produces the file not found issues. So symlinks work for the appserver but not for `php-fpm` as our default FastCGI backend when it comes to script handling. :(

There is no simple way to debug such issues but best indicator is the `X-Powered-By` header field of the HTTP response. This shows by which module the request has been handled. If you have a look at the [configured module chain](https://github.com/appserver-io/appserver/blob/master/resources/templates/etc/appserver/appserver.xml.phtml#L258) you will see where the request has been dropped from.
A general symlink error would be the `CoreModule` with a `404` whereas the error comes from the `FastCgiModule.
I will extend the error description accordingly.

What are you evaluation the appserver for if I may ask?
You can also join [our support chat](https://gitter.im/appserver-io/appserver) if there any further questions :)

**Comment by lekoala** [comment]
Yes it works indeed. I thought it wasn't because during my initial tests I didn't change the permissions correctly.

I'm evaluating appserver because I've been developing with a cms called Silverstripe for a while, but I'm starting to face performance issue and cron jobs/queues are just a real pain to set up properly, and I'm very interested by the ability to bootstrap some code for all requests and be able to use the timer service.

So my first test was simply to see if Silverstripe is running on appserver and in which way I could use its infrastructure.

I have to say that appserver seems to be a wonderful product when you see what it helps to solve, and I was wondering if I could use it for future developments.

**Comment by wick-ed** [comment]
Thanks for the praise. :)

Unfortunately I cannot offer you a fast solution. For the time being you might be forced to directly work within the `webapps` directory or use some kind of deployment mechanism [like we do](https://github.com/appserver-io-apps/example/blob/master/build.xml#L119).
Better symlinking will be worked on. :)

For basically running Silverstripe you should not face any problems, as we forward every "legacy application" to `php-fpm`.
For using additional features you must wrap your CMS into a webapp skeleton and depending on the depth you want to integrate it in some servlets/beans/etc.

**Comment by lekoala** [comment]
Just a few more questions

1. Why isn't it possible to change the server root to another directory outside of the directory of appserver, like apache does? This way there is no need to use symlinks, deploy mechanisms, etc

2. How could I run a legacy application if php files are not executed properly outside of the web root ? I guess the only way currently is to deploy it inside the webapps folder?

3. Is there any open source cms that already leverages appserver architecture? Or any other applications by the way, I don't see any list anywhere?

**Comment by wick-ed** [comment]
Hi @lekoala ,

no problem. :)

1. This is the cause for this ticket and something we consider a bug. We do intend to enable document roots outside of default one. This will only be a matter of time.

2. Yes, that's correct. Currently the only verified way to make it work is deploying it within the `webapps` folder. :(

3. There are several we tried which worked well, have a look at [our tutorials](http://appserver.io/get-started/tutorials.html). Actual everything that works on apache or nginx should work on appserver.io as we use the same mechanism for script execution but there is no CMS I know of which makes greater use of appserver features like the TimerService or the MQ.
