### ISSUE TITLE
[appserver-io/doppelgaenger] Call to a protected method errors due to context mismatch

### ISSUE THREAD

**Issue by welly275** [appserver-io/appserver#855]
PHP Fatal error:  Call to protected method AppserverIo\Doppelgaenger\Parser\TraitParser::getAttributeProperties() from context 'AppserverIo\Doppelgaenger\Parser\TraitParser' in /opt/appserver/vendor/appserver-io/doppelgaenger/src/Parser/PropertyParserTrait.php on line 90

**Comment by wick-ed** [comment]
Hi there @welly275 ,

which version of `appserver-io/doppelgaenger` do you use? This issue seems to be related to a behavior occuring together with the `pthreads` extension.
There is [a fix](https://github.com/appserver-io/doppelgaenger/releases/tag/1.4.2) available with `doppelgaenger` version 1.4.2

Please recheck and come back for confirmation or further support. :)

**Comment by welly275** [comment]
i am using the 1.4.4

**Comment by welly275** [comment]
is there something that has to be configured? because on every restart i am getting that php error.

**Comment by wick-ed** [comment]
No, this is no configuration problem. It seems to be related to `pthreads` context separation and the inheritance of class definitions in between these contexts.
Must be based on the specific timing of your machine as it did not show anywhere else.

I will release a patch for that asap.

**Comment by welly275** [comment]
it might be. thank you for your attention.

**Comment by wick-ed** [comment]
Should be fixed with [this release](https://github.com/appserver-io/doppelgaenger/releases/tag/1.4.5)
