### ISSUE TITLE
How I can add PHP extension like MongoDB driver so that I can use it in appserver?

### ISSUE THREAD

**Issue by rs-rawat** [appserver-io/appserver#903]
I am trying to create an application using Appserver + MySql + MongoDB. Don't know how to add PHP extension in Appserver 1.06.

**Comment by wagnert** [comment]
Hi, you can either compile it by yourself like described on the [MongoDB driver description](http://php.net/manual/de/mongo.installation.php) 
```sh
$ tar zxvf mongodb-mongodb-php-driver-<commit_id>.tar.gz
$ cd mongodb-mongodb-php-driver-<commit_id>
$ /opt/appserver/bin/phpize
$ ./configure
$ make all
$ sudo make install
```
or otherwise, if the extension you want to add is a PECL extension, you can use the pecl command under `/opt/appserver/bin/pecl` to install the extension.

In both cases, please always remember to use the binaries under `/opt/appserver/bin` instead of using your system ones. This is necessary, because we've a thread safe compiled PHP.
