### ISSUE TITLE
[legal] Can I develop fully commercial and paid CMS on appserver.io?

### ISSUE THREAD

**Issue by fazliddin** [appserver-io/appserver#942]
I saw that your project uses OSL. But it is not clear for me whether I can develop web applications like CMS and CRM using (linking) appserver.io and take patent for my derivate work and sell licenses for my applications?

Also I could not understand will I have to distribute appserver.io with my app or not. The reason why I am asking this question is that no php application is distributed with apache, but how about appserver.io case?

**Comment by smolinari** [comment]
I am not an appserver team member, but I'd say the answer to your questions is yes and yes. 

As for the second question, it would be better to get your future user to understand your software is built for appserver and not for a standard LAMP or LEMP stack. That way, it is up to the user to install and run the server properly. 

Hopefully (and I am positive one will come too) one of the appserver team will answer to give you an official answer.

Scott

**Comment by wagnert** [comment]
Hi @fazliddin, and thanks to @smolinari :)

You can develop and sell web applications like CRM or CMS running on appserver.io. You can also sell licences for your web applications. If you need more legal details, i would recommend to write an email to our legal department (gs@appserver.io) with an brief description what you plan to do. As Guido, the guy who takes care on all questions about legal stuff, is in his christmas vacation, you'll receveive an answer as soon as he'll be back, i think that'll be in early january.

As Scott explained, if you develop your application for appserver.io, you've to be aware, that you or your customers need a running appserver.io installation to deploy your web application. It's up to you, if you want to deliver your web application bundled with appserver.io or not. If not, your customers have to install appserver.io and deploy your web application by themselves.

I hope, i was able to answer your questions properly. If not, feel free to ask again :)

Best Regards
Tim

**Comment by fazliddin** [comment]
Thank you Tim and Scott.

What we want to build is enterprise framework and general purpose CMS with CRM and ERP modules on appserver.io. After carefully reading OSL v3.0, I understood that our work becomes independent work and is not subject to OSL license, since we do not change appserver, but only extent its class (please, correct me if I am not right).

Our solution is offered as service and as software for download. Due to OSL's External Deployment condition we should make appserver source code available to each user who visits our SAS website. But on the other hand user will be interacting with our non OSL software. So my question is whether we should make appserver code available to every website user? if yes, in what form we should do it?

**Comment by wagnert** [comment]
@fazliddin I think it's not necessary to make the appserver.io code available to every website user, as it is already available through the Github repository. I think it should be enough, if you add a statement about appserver.io (like build on appserver.io) and a link to appserver.io website. As i'm not really have a deep legal knowledge about OSL 3.0, i would request Guido to give you an exact explanation of what would be necessary, hoping that this will be o. k. for you :)

**Comment by fazliddin** [comment]
Fine! Your info was very helpful for me. I will be contacting to Guido for further legal questions. I hope we will have long term partnership.

**Comment by smolinari** [comment]
I need to revise my answer, and sorry for the confusion. The answer to your second question is no. You don't need to distribute appserver with your application (and you shouldn't really). I have no idea why I said yes. LOL!. Though my first answer sort of shows I was thinking in the right direction. It is exactly as you mentioned it and just like as if your customers would be using Apache or Nginx. They can run their server with appserver and pay for your application to run on top of appserver, but sold/ offered separately from each other. 

As I understand OSL, once you do start to distribute appserver, then whatever it is you distribute is a derivative of appserver (even with a complicated application on top of it) and thus, must also be distributed as OSL software. So, in effect, you must NOT distribute appserver, if you intend to sell your application. 

I am not a lawyer, so take that with a pinch of salt. Best to talk to Guido for sure. :smile: 

Scott

**Comment by wagnert** [comment]
@fazliddin Guido will for sure give you the necessary information. We'll also hope to have a long term partnership, maybe you should have a look at our partner programs, probably there one of the options will fit your needs :)
@smolinari Thanks for clearifying :)

**Comment by siegerg** [comment]
Hi @fazliddin,

you had a couple of legal questions about using appserver.io for your project. Since Tim and Scott enlightened you already, I have a little less work after my holiday :-) Thanks for that!

Basically the OSL-3.0 grants you to do whatever you want, if you change nothing within the appserver.io Software and accompaning documents (license, documentation, etc.). As far as I understood you, you just want to use appserver.io as a basic infrastructure without changing anything within the software (you described it as "linking"). Then you are free to do so.

Only if you translate, adapt, alter, transform, modify, or arrange the Original Work you will create a "Derivative Work" which would then also fall under the OSL-3.0 (§ 1 Abs. b) OSL-3.0).

Concerning our software you are also free to choose what you want to do. You can deliver appserver.io with your commercial software in a bundle thus creating a collective work (§ 1 Abs. a) OSL-3.0). Your software will not fall under the OSL-3.0 in this case. You could also (don't have to) provide a link to our website or github on your website where your customers can download the appserver.io Software. You can even market your software with the appserver.io logo and e.g. "works with / made for / powered by" etc. In case you need something: we have a press kit free to use along with our trademark- and logoguide. Both will be available on our website anytime soon; if you need it upfront, just send me an email.

If you discover while developing your software, that it is actually necessary to alter code of the free version of appserver.io you should talk to us for an individual solution. Since we hold the copyright of the software, we can always grant you an individual proprietary license that fits your needs.

If your software is intended for the enterprise segment you might need a more sophisticated version of appserver.io which provides high availability and scalability for the professional use. At the moment we are working on a Enterprise Edition which will deliver features like farming deployment, clustering and many more. In case you might want to bundle appserver.io Enterprise Edition with your software please feel free to contact me directly. We have already developed different Partner Programms which allow you e.g. to bundle the software or resell it.

If you have any additional questions, I'll be glad to help you.

Best wishes
Guido

**Comment by fazliddin** [comment]
Thank you @siegerg!

**Comment by wagnert** [comment]
@fazliddin As i think we could answer all questions, i'll close that issue 😀
